### PR TITLE
test

### PR DESCRIPTION
**Pull request by klainfo**

### CODE REVIEW

**Comment by wudylk** [comment]
I recieved the 8th pull request action

**Comment by wudylk** [comment]
I recieved the 9th pull request action

**Comment by wudylk** [comment]
I recieved the 10th pull request action

**Comment by wudylk** [comment]
I recieved the 11th pull request action

**Comment by wudylk** [comment]
I recieved the 12th pull request action

**Comment by wudylk** [comment]
I recieved the 1th pull request action

**Comment by wudylk** [comment]
I recieved the 2th pull request action

**Comment by samwang90** [comment]
<html>


</html>

**Comment by samwang90** [comment]
<h1>hahaha<h1>

**Comment by samwang90** [comment]
(test picture)[https://github.com/wudylk/TestRepo/blob/master/test_bug.png]

**Comment by samwang90** [comment]
[test picture](https://github.com/wudylk/TestRepo/blob/master/test_bug.png)

**Comment by samwang90** [comment]
Result Picture

**Comment by samwang90** [comment]
Architecture Picture

**Comment by samwang90** [comment]
Google Picture

**Comment by wudylk** [comment]
I recieved the 1th pull request action

**Comment by wudylk** [comment]
I recieved the 2th pull request action

**Comment by wudylk** [comment]
Please check those commit before merge.
Click commits for more prediction information.

**Comment by wudylk** [comment]
The commit 7b7fb2eca51dacb5002a4e6b6e1417b36bd5dfd7 seems buggy at 66% confidence.
The commit e1816669732c54c40122c8a22dcba42f6ee3c326 seems buggy at 27% confidence.
The commit 83b04d4f88dd65ae630a45385de34e275899dc41 seems buggy at 97% confidence.
The commit f2d5dafec93e6b3100f004c559ebe21e2b783ae7 seems buggy at 9% confidence.
Please check those commit before merge.
Click commits for more prediction information.

**Comment by wudylk** [comment]
f2d5dafec93e6b3100f004c559ebe21e2b783ae7

**Comment by wudylk** [comment]
The commit 7b7fb2eca51dacb5002a4e6b6e1417b36bd5dfd7 seems buggy at 66% confidence.
The commit e1816669732c54c40122c8a22dcba42f6ee3c326 seems buggy at 27% confidence.
The commit 83b04d4f88dd65ae630a45385de34e275899dc41 seems buggy at 97% confidence.
The commit f2d5dafec93e6b3100f004c559ebe21e2b783ae7 seems buggy at 9% confidence.
Please check those commit before merge.
Click commits for more prediction information.

**Comment by wudylk** [comment]
The commit 7b7fb2eca51dacb5002a4e6b6e1417b36bd5dfd7 seems buggy at 66% confidence.
The commit e1816669732c54c40122c8a22dcba42f6ee3c326 seems buggy at 27% confidence.
The commit 83b04d4f88dd65ae630a45385de34e275899dc41 seems buggy at 97% confidence.
The commit f2d5dafec93e6b3100f004c559ebe21e2b783ae7 seems buggy at 9% confidence.
Please check those commit before merge.
Click commits for more prediction information.

**Comment by wudylk** [comment]
The commit 7b7fb2eca51dacb5002a4e6b6e1417b36bd5dfd7 seems buggy at 66% confidence.
The commit e1816669732c54c40122c8a22dcba42f6ee3c326 seems buggy at 27% confidence.
The commit 83b04d4f88dd65ae630a45385de34e275899dc41 seems buggy at 97% confidence.
The commit f2d5dafec93e6b3100f004c559ebe21e2b783ae7 seems buggy at 9% confidence.
Please check those commit before merge.
Click commits for more prediction information.

**Comment by wudylk** [comment]
The commit 7b7fb2eca51dacb5002a4e6b6e1417b36bd5dfd7 seems buggy at 66% confidence.
The commit e1816669732c54c40122c8a22dcba42f6ee3c326 seems buggy at 27% confidence.
The commit 83b04d4f88dd65ae630a45385de34e275899dc41 seems buggy at 97% confidence.
The commit f2d5dafec93e6b3100f004c559ebe21e2b783ae7 seems buggy at 9% confidence.
Please check those commit before merge.
Click commits for more prediction information.

**Comment by wudylk** [comment]
The commit 7b7fb2eca51dacb5002a4e6b6e1417b36bd5dfd7 seems buggy at 66% confidence.
The commit e1816669732c54c40122c8a22dcba42f6ee3c326 seems buggy at 27% confidence.
The commit 83b04d4f88dd65ae630a45385de34e275899dc41 seems buggy at 97% confidence.
The commit f2d5dafec93e6b3100f004c559ebe21e2b783ae7 seems buggy at 9% confidence.
Please check those commit before merge.
Click commits for more prediction information.

**Pull request closed without merging**
